### ISSUE TITLE
Use Combat Options icon (crossed swords) to represent required combat level

### ISSUE THREAD

**Issue by ErikHumphrey** [cesoun/optimal-quest-guide#11]
Rather than ![(c)](https://github.com/cesoun/optimal-quest-guide/blob/master/src/main/resources/combat_level.png?raw=true), use the icon for the ![Combat Options](https://oldschool.runescape.wiki/images/8/8c/Attack_style_icon.png?ceb2e) Combat Options interface to represent required combat levels, similar to the icon used on the Wiki.

**Comment by cesoun** [comment]
Closed by 684e74f3ddb12eed4c45a0c3244358aee749587d
