### ISSUE TITLE
Completed quests showing incorrectly

### ISSUE THREAD

**Issue by Deathomen** [cesoun/optimal-quest-guide#25]
I noticed yesterday that the plugin is showing a subset of quests that I have already completed, even though I don't have that option enabled in the config. I've tried rebooting both Runelite and my PC, logging in to a different account then back to my main, and uninstalling and reinstalling the plugin, but nothing has resolved the issue.

**Comment by cesoun** [comment]
I've had a few reports from multiple users on this and will be digging into it when I return from vacation. Seems to have happened sometime during the last PR I merge in from what I can tell.

Below are some images a user sent to check locally later for consistency. 


![Example 1](https://user-images.githubusercontent.com/8537054/125148313-60306a00-e0ff-11eb-97a6-57ff32804fe4.png)

![Example 2](https://user-images.githubusercontent.com/8537054/125148325-6f171c80-e0ff-11eb-847f-ecaa1244fd65.png)

**Comment by Deathomen** [comment]
Thanks for the quick reply! This lines up pretty much exactly with what I'm seeing. Enjoy your vacation and we can sort this out when you return :D

**Comment by Deathomen** [comment]
Just wanted to drop by to let you know that this issue seems to be resolved, however I don't see any new updates here in Github since the last time. Maybe this was an issue on the RS side?

**Comment by cesoun** [comment]
I am seeing the same thing. There might have been some changes within QuestState during a RuneLite update but it seems to have resolved itself. I'll go ahead an close this for now but in the case that it does return I'll just reopen this issue. 

Thanks.
