### ISSUE TITLE
New quest missing: Beneath cursed sands

### ISSUE THREAD

**Issue by treichold** [cesoun/optimal-quest-guide#32]
Good afternoon from Germany!

The new quest Beneath cursed sands is missing from my quest helper.
Has this already been added and not displayed or has this one not yet been added?
If not is there a release date for it?

Kind regards

**Comment by treichold** [comment]
Dear Cesoun,

Cheers for the update. I'm not well versed in this type of processes so I will wait for your official inclusion.

Kind regards

**Comment by cesoun** [comment]
Long overdue, closed by be32dfc596e8ec5c49764d9625fd732e5a48f24b
